repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        entry: pflake8
        args: [--config, 'pyproject.toml']
        additional_dependencies:
        -   pyproject-flake8
        -   flake8-bugbear
        -   flake8-print
        -   flake8-import-order

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
    -   id: mypy
        args: ['--config-file', 'pyproject.toml']
