"""init

Revision ID: edf577c8bdb4
Revises:
Create Date: 2023-10-13 12:01:46.486550

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = 'edf577c8bdb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
